colors = "always"
pager = "always"
unrecorded_changes = 1

[author]
name = "sebaschi"
full_name = "Sebastian Lenzlinger"
email = "eswer@eswo.ch"
key_path = "/home/seb/.ssh/id_ed25519.pub"

[ignore_kinds]
rust = ["target", "*.perf"]
python = [ "dist", "build", "eggs", "__pycache__"]
