#
# eza aliases
#
alias ll='eza -l'
alias la='eza -la'
alias lll='eza -la -T -l --level=3'
alias lla='eza -laF'
alias la='eza -A'
alias l='eza -CF'

#
## Git aliases
#
alias g='git'
alias gs='git status'
alias ga='git add'
alias gaa='git add --all'

alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit --amend'

alias gco='git checkout'
alias gcb='git checkout -b'

alias gcp='git cherry-pick'
alias gcl='git clone'   

alias gplr='git pull --rebase'
alias gpl='git pull'
alias gpo='git push origin'
alias gpf='git push --force'
# git log aliases
alias glog='git log --oneline --graph --decorate'
alias gloga='git log --oneline --graph --decorate --all'
alias glod='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset"'
alias glods='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset" --date=short'

#termbin
alias tb='nc termbin.com 9999'

# get error messages from journalctl
alias jerr='journalctl -p 3 -xb'
# get warning messages from journalctl
alias jwarn='journalctl -p 4 -xb'
# get critical messages from journalctl
alias jcrit='journalctl -p 2 -xb'
# get emergency messages from journalctl
alias jemerg='journalctl -p 0 -xb'

# get status of all services
alias jstat='systemctl list-units --type=service --state=running'
# get status with failed services
alias jstatf='systemctl list-units --type=service --state=failed'

# history
alias histg='history | grep'

# get my ip
alias myip='curl ifconfig.me'
#TODO: get my ipv4
