fastfetch 

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

unset rc

source /home/slnopriv/alacritty/extra/completions/alacritty.bash
eval "$(starship init bash)"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/slnopriv/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/slnopriv/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/slnopriv/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/slnopriv/anaconda3/bin:$PATH"
    fi
fi

export PATH="$PATH:/home/slnopriv/Applications/pycharm-2023.2.3/bin"
export PATH="$PATH:/home/slnopriv/Applications/DataGrip-2023.2.2/bin"

unset __conda_setup
# <<< conda initialize <<<

# cd to fs23 pids exercises
alias cdpex='cd ~/Documents/Education/UniBas/FS23/pids23/exercises/pids_2023/exercises/'

# cd into nextcloud unibas fs23
alias uni23='cd ~/Nextcloud/Documents/Unibas/HS23/'

#cd into thoc
alias thoc='cd ~/Nextcloud/Documents/Unibas/FS23/thoc/'
#cd into inetsec 
alias inetsec='cd ~/Nextcloud/Documents/Unibas/FS23/inetsec/'
#cd into os alias 
alias os='cd ~/Nextcloud/Documents/Unibas/FS23/os/' 
#cd into pkvps 
alias pkvps='cd ~/Nextcloud/Documents/Unibas/FS23/pkvps/'
#cd into pids
alias pids='cd ~/Nextcloud/Documents/Unibas/FS23/pids/'

alias pr23='cd ~/Documents/Education/UniBas/HS23/pr23/'
alias db23='cd ~/Documents/Education/UniBas/HS23/databases/'
alias pet23='cd ~/Documents/Education/UniBas/HS23/pethpc23/'
alias diskmath='cd ~/Documents/Education/UniBas/HS23/diskmath-tutorat23/'

#rsync Books from Cloud
alias pullbooks='rsync -av ~/Nextcloud/Books/ ~/Books'
alias pushbooks='rsync -av ~/Books/ ~/Nextcloud/Books'
alias pushhs23='rsync -uav --exclude=".*" --exclude="__*" ~/Documents/Education/UniBas/HS23/ ~/Nextcloud/Documents/Unibas/HS23'
alias pullhs23='rsync -uav --exclude=".*" ~/Nextcloud/Documents/Unibas/HS23/ ~/Documents/Education/UniBas/HS23'

alias unil='cd ~/Documents/Education/UniBas/HS23'
alias unic='cd ~/Nextcloud/Documents/Unibas/FS23'

# ssh to wherever slnopriv@slenzlinger.dev points to
alias sdev='ssh sebl@slenzlinger.dev'
alias sslenz='ssh fm18b_sebaschi@slenzlinger.ch'

# exa aliases
alias ll='exa -l'
alias la='exa -la'

alias lll='exa -la -T -l --level=3'
alias lla='exa -laF'
alias la='exa -A'
alias l='exa -CF'

